# Generated by Django 3.1.7 on 2021-04-30 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_auto_20210424_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.share'),
        ),
    ]
